# PID of current job: 206034
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 10, "none", -1, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "SumNorm", "LogNorm", "ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-GetGroupNames(mSet, "")
feature.nm.vec <- c("")
smpl.nm.vec <- c("")
grp.nm.vec <- c("con_9","dro_9","foc_9","xvm_9")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_2_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_2_", "png", 72, width=NA)
feature.nm.vec <- c("")
smpl.nm.vec <- c("F9.4")
grp.nm.vec <- c("con_9","dro_9","foc_9","xvm_9")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_3_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_3_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "NULL", "NULL", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_4_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_4_", "png", 72, width=NA)
mSet<-Normalization(mSet, "SumNorm", "LogNorm", "ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_5_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_5_", "png", 72, width=NA)
mSet<-Normalization(mSet, "QuantileNorm", "LogNorm", "ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_6_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_6_", "png", 72, width=NA)
mSet<-Normalization(mSet, "QuantileNorm", "NULL", "NULL", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_7_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_7_", "png", 72, width=NA)
mSet<-Normalization(mSet, "QuantileNorm", "LogNorm", "ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_8_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_8_", "png", 72, width=NA)
mSet<-Normalization(mSet, "SumNorm", "LogNorm", "ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_9_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_9_", "png", 72, width=NA)
mSet<-Normalization(mSet, "SumNorm", "NULL", "NULL", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_10_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_10_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_11_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_11_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "NULL", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_12_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_12_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "MeanCenter", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_13_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_13_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "RangeNorm", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_14_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_14_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "AutoNorm", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_15_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_15_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "NULL", "AutoNorm", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_16_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_16_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "NULL", "NULL", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_17_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_17_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-UpdateLoadingCmpd(mSet, "M1059.46T14.114")
mSet<-SetCmpdSummaryType(mSet, "violin")
mSet<-PlotCmpdSummary(mSet, "M1059.46T14.114","NA","NA", 0, "png", 72)
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M1059.46T14.114","NA","NA", 1, "png", 72)
mSet<-Calculate.ANOVA.posthoc(mSet, "fisher", 0.05)
mSet<-ANOVA.Anal(mSet, F, 1.0, FALSE)
mSet<-PlotANOVA(mSet, "aov_1_", "png", 72, width=NA)
mSet<-Calculate.ANOVA.posthoc(mSet, "tukey", 0.05)
mSet<-ANOVA.Anal(mSet, F, 1.0, FALSE)
mSet<-PlotANOVA(mSet, "aov_2_", "png", 72, width=NA)
mSet<-UpdateLoadingCmpd(mSet, "M1356.732T13.109")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M1356.732T13.109","NA","NA", 2, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M882.812T18.125")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M882.812T18.125","NA","NA", 3, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M1522.706T13.16")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M1522.706T13.16","NA","NA", 4, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M354.284T1595.998")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M354.284T1595.998","NA","NA", 5, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M1059.46T14.114")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M1059.46T14.114","NA","NA", 6, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M1067.787T17.122")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M1067.787T17.122","NA","NA", 7, "png", 72)
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 72, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, T, T, NULL, T, F, T, T,  T,T)
mSet<-SaveTransformedData(mSet)
