# PID of current job: 759862
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 25, "iqr", 5, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-GetGroupNames(mSet, "")
feature.nm.vec <- c("")
smpl.nm.vec <- c("C12.1","F12.3")
grp.nm.vec <- c("Control","Drought","Fusarium","Xanthomonas")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 25, "iqr", 0, "mean", 0)
mSet<-PreparePrenormData(mSet)
feature.nm.vec <- c("")
smpl.nm.vec <- c("C12.1","F12.3")
grp.nm.vec <- c("Control","Drought","Fusarium","Xanthomonas")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-UpdateLoadingCmpd(mSet, "M619.438T1245.233")
mSet<-SetCmpdSummaryType(mSet, "violin")
mSet<-PlotCmpdSummary(mSet, "M619.438T1245.233","NA","NA", 0, "png", 72)
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M619.438T1245.233","NA","NA", 1, "png", 72)
mSet<-GetGroupNames(mSet, "null")
colVec<-c("##00ac0e","##abe65d","##145fc8","##6ab5ff")
shapeVec<-c(0,0,0,0)
mSet<-UpdateGraphSettings(mSet, colVec, shapeVec)
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M619.438T1245.233","NA","NA", 2, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M576.533T1641.124")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M576.533T1641.124","NA","NA", 3, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M542.478T1573.977")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M542.478T1573.977","NA","NA", 4, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M383.284T1439.726")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M383.284T1439.726","NA","NA", 5, "png", 72)
mSet<-ANOVA.Anal(mSet, T, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_1_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_2_", "png", 72, width=NA)
mSet<-UpdateLoadingCmpd(mSet, "M619.438T1245.233")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M619.438T1245.233","NA","NA", 6, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M576.484T1473.551")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M576.484T1473.551","NA","NA", 7, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M609.455T1145.906")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M609.455T1145.906","NA","NA", 8, "png", 72)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_1_", "png", 72, width=NA, 1,2,0.95,1,0, "na")
mSet<-PlotPLS2DScore(mSet, "pls_score2d_2_", "png", 72, width=NA, 1,2,0.95,1,1, "na")
mSet<-PlotPLS2DScore(mSet, "pls_score2d_3_", "png", 72, width=NA, 1,2,0.95,1,0, "na")
mSet<-PlotPLS2DScore(mSet, "pls_score2d_3_", "png", 300, width=NA, 1,2,0.95,1,0, "na")
mSet<-PlotPLS2DScore(mSet, "pls_score2d_3_", "pdf", 72, width=NA, 1,2,0.95,1,0, "na")
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, T, T, NULL, T, F, T, T,  T,T)
mSet<-PlotCorrHeatMap(mSet, "corr_1_", "png", 72, width=NA, "col", "pearson", "bwm", F, F, 6, 10, 0.0)
mSet<-FeatureCorrelation(mSet, "pearson", "M285.134T1052.907")
mSet<-PlotCorr(mSet, "ptn_0_", "feature", "png", 72, width=NA)
mSet<-ComputeDSPC(mSet)
mSet<-CreateGraph(mSet)
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 72, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)
mSet<-SaveTransformedData(mSet)
