# PID of current job: 1011958
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 25, "iqr", 0, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-GetGroupNames(mSet, "")
feature.nm.vec <- c("")
smpl.nm.vec <- c("F9.4","C12.1","F12.3")
grp.nm.vec <- c("First-tp_Control","First-tp_Drought","First-tp_Fusarium","First-tp_Xanthomonas","Second-tp_Control","Second-tp_Drought","Second-tp_Fusarium","Second-tp_Xanthomonas")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, T, T, NULL, T, F, T, T,  T,T)
mSet<-PlotHeatMap(mSet, "heatmap_2_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 2, T, T, NULL, T, F, T, T,  T,F)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 1.0, FALSE)
mSet<-PlotANOVA(mSet, "aov_1_", "png", 72, width=NA)
mSet<-Calculate.ANOVA.posthoc(mSet, "fisher", 0.05)
mSet<-ANOVA.Anal(mSet, F, 0.051556, FALSE)
mSet<-PlotANOVA(mSet, "aov_2_", "png", 72, width=NA)
mSet<-PlotSubHeatMap(mSet, "heatmap_3_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 2, "tanova", 633, T, T, T, F, T, T, T,F,"overview")
mSet<-GetGroupNames(mSet, "null")
colVec<-c("##d8a8ff","#NA","#NA","#NA","#NA","#NA","#NA","#NA")
shapeVec<-c(0,0,0,0,0,0,0,0)
mSet<-UpdateGraphSettings(mSet, colVec, shapeVec)
colVec<-c("##d8a8ff","##ff821c","##ffc982","##ff0000","#NA","#NA","#NA","#NA")
shapeVec<-c(0,0,0,0,0,0,0,0)
mSet<-UpdateGraphSettings(mSet, colVec, shapeVec)
mSet<-PlotSubHeatMap(mSet, "heatmap_4_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 2, "tanova", 633, T, T, T, F, T, T, T,F,"overview")
colVec<-c("##d8a8ff","##ff821c","##ffc982","##ff0000","#NA","#NA","#NA","#NA")
shapeVec<-c(0,0,0,0,0,0,0,0)
mSet<-UpdateGraphSettings(mSet, colVec, shapeVec)
mSet<-PlotSubHeatMap(mSet, "heatmap_4_", "pdf", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 2, "tanova", 633, T, T, T, F, T, T, T,F,"overview" , T)
colVec<-c("##d8a8ff","##ff821c","##ffc982","##ff0000","##4aa341","##aff7b0","##5089f2","##65c1e8")
shapeVec<-c(0,0,0,0,0,0,0,0)
mSet<-UpdateGraphSettings(mSet, colVec, shapeVec)
mSet<-PlotSubHeatMap(mSet, "heatmap_4_", "pdf", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 2, "tanova", 633, T, T, T, F, T, T, T,F,"overview" , T)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-SaveTransformedData(mSet)
