# PID of current job: 1936659
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 25, "iqr", 0, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-GetGroupNames(mSet, "")
feature.nm.vec <- c("")
smpl.nm.vec <- c("X44.D12.1.neg","X09.X12.3.neg")
grp.nm.vec <- c("Drought","Fusarium","Mock","Xanthomonas")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 72, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_1_", "png", 72, width=NA, 1,2,0.95,1,0, "decrease")
mSet<-GetGroupNames(mSet, "null")
mSet<-PlotPCA2DScore(mSet, "pca_score2d_1_", "png", 300, width=NA, 1,2,0.95,1,0, "decrease")
mSet<-PlotPCA2DScore(mSet, "pca_score2d_1_", "pdf", 72, width=NA, 1,2,0.95,1,0, "decrease")
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_1_", "png", 72, width=NA, 1,2,0.95,1,0, "decrease")
mSet<-PlotPLS2DScore(mSet, "pls_score2d_2_", "png", 72, width=NA, 1,2,0.95,0,0, "decrease")
mSet<-PlotPLS2DScore(mSet, "pls_score2d_2_", "pdf", 72, width=NA, 1,2,0.95,0,0, "decrease")
mSet<-PlotPLS2DScore(mSet, "pls_score2d_2_", "png", 300, width=NA, 1,2,0.95,0,0, "decrease")
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, T, T, NULL, T, F, T, T,  T,T)
mSet<-PlotHeatMap(mSet, "heatmap_2_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,10, 10, T, T, NULL, T, F, T, T,  T,F)
mSet<-PlotStaticHeatMap(mSet, "heatmap_2_", "pdf", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, "overview", T, T, NULL, T, F, T, T, F)
mSet<-PlotHeatMap(mSet, "heatmap_3_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,11, 20, T, T, NULL, T, F, T, T,  T,F)
mSet<-PlotStaticHeatMap(mSet, "heatmap_3_", "pdf", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, "overview", T, T, NULL, T, F, T, T, F)
mSet<-SaveTransformedData(mSet)
