# PID of current job: 3017182
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 25, "iqr", 0, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-GetGroupNames(mSet, "")
feature.nm.vec <- c("")
smpl.nm.vec <- c("BLANK.2","F9.4","C12.1","F12.3","D15.1","D15.3","D15.4","F15.1","F15.3")
grp.nm.vec <- c("Control","Drought","Fusarium","Other","Xanthomonas")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, T, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_1_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, T, 1.0, FALSE)
mSet<-PlotANOVA(mSet, "aov_2_", "png", 72, width=NA)
mSet<-Calculate.ANOVA.posthoc(mSet, "fisher", 0.05)
mSet<-ANOVA.Anal(mSet, T, 0.24316, FALSE)
mSet<-PlotANOVA(mSet, "aov_3_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, T, 0.24316, FALSE)
mSet<-PlotANOVA(mSet, "aov_4_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 1.0, FALSE)
mSet<-PlotANOVA(mSet, "aov_5_", "png", 72, width=NA)
mSet<-Calculate.ANOVA.posthoc(mSet, "fisher", 0.05)
mSet<-ANOVA.Anal(mSet, F, 0.29909, FALSE)
mSet<-PlotANOVA(mSet, "aov_6_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, T, 0.24316, FALSE)
mSet<-PlotANOVA(mSet, "aov_7_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.29909, FALSE)
mSet<-PlotANOVA(mSet, "aov_8_", "png", 72, width=NA)
mSet<-UpdateLoadingCmpd(mSet, "M753.276T940.951")
mSet<-SetCmpdSummaryType(mSet, "violin")
mSet<-PlotCmpdSummary(mSet, "M753.276T940.951","NA","NA", 0, "png", 72)
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M753.276T940.951","NA","NA", 1, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M753.276T940.951")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M753.276T940.951","NA","NA", 2, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M465.265T1237.073")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M465.265T1237.073","NA","NA", 3, "png", 72)
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, T, T, NULL, T, F, T, T,  T,T)
mSet<-PlotSubHeatMap(mSet, "heatmap_2_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, "tanova", 382, T, T, T, F, T, T, T,T,"overview")
mSet<-PlotSubHeatMap(mSet, "heatmap_3_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, "tanova", 382, F, T, T, F, T, T, T,T,"overview")
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 72, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_1_", "png", 72, width=NA, 1,2,0.95,1,0, "decrease")
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-SaveTransformedData(mSet)
