# PID of current job: 558341
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 25, "iqr", 0)
mSet<-PreparePrenormData(mSet)
mSet<-GetGroupNames(mSet, "")
feature.nm.vec <- c("")
smpl.nm.vec <- c("")
grp.nm.vec <- c("con_12","dro_12","foc_12","xvm_12")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-PlotHeatMap(mSet, "heatmap_0_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8, "overview", T, T, NULL, T, F, T, T, T)
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8, "overview", F, T, NULL, T, F, T, T, T)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 1.0, FALSE)
mSet<-PlotANOVA(mSet, "aov_1_", "png", 72, width=NA)
mSet<-Calculate.ANOVA.posthoc(mSet, "tukey", 0.05)
mSet<-ANOVA.Anal(mSet, F, 0.79926, FALSE)
mSet<-PlotANOVA(mSet, "aov_2_", "png", 72, width=NA)
mSet<-Calculate.ANOVA.posthoc(mSet, "tukey", 0.05)
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 72, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_1_", "png", 72, width=NA, 1,2,0.95,1,0)
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotSubHeatMap(mSet, "heatmap_2_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8, "tanova", 145, "overview", T, T, T, F, T, T, T)
mSet<-SaveTransformedData(mSet)
