# PID of current job: 871573
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 10, "iqr", 5, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "SumNorm", "LogNorm", "ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "NULL", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-GetGroupNames(mSet, "")
feature.nm.vec <- c("")
smpl.nm.vec <- c("")
grp.nm.vec <- c("con_12","dro_12")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "NULL", "Sodium_Formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_2_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_2_", "png", 72, width=NA)
mSet<-FC.Anal(mSet, 2.0, 0, FALSE)
mSet<-PlotFC(mSet, "fc_0_", "png", 72, width=NA)
mSet<-FC.Anal(mSet, 1.0, 1, FALSE)
mSet<-PlotFC(mSet, "fc_1_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, TRUE, "fdr", FALSE)
mSet<-PlotTT(mSet, "tt_0_", "png", 72, width=NA)
mSet<-FC.Anal(mSet, 1.0, 0, FALSE)
mSet<-PlotFC(mSet, "fc_2_", "png", 72, width=NA)
mSet<-FC.Anal(mSet, 1.0, 1, FALSE)
mSet<-PlotFC(mSet, "fc_3_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, FALSE, "raw", FALSE)
mSet<-PlotTT(mSet, "tt_1_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, FALSE, "raw", FALSE)
mSet<-PlotTT(mSet, "tt_2_", "png", 72, width=NA)
mSet<-UpdateLoadingCmpd(mSet, "M830.837T11.111")
mSet<-SetCmpdSummaryType(mSet, "violin")
mSet<-PlotCmpdSummary(mSet, "M830.837T11.111","NA","NA", 0, "png", 72)
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M830.837T11.111","NA","NA", 1, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M883.492T15.092")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M883.492T15.092","NA","NA", 2, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M367.151T397.982")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M367.151T397.982","NA","NA", 3, "png", 72)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, F, 0.1, TRUE, "raw")
mSet<-PlotVolcano(mSet, "volcano_0_",1, 0, "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 1.0, 1, F, 0.05, FALSE, "raw")
mSet<-PlotVolcano(mSet, "volcano_1_",1, 0, "png", 72, width=NA)
mSet<-UpdateLoadingCmpd(mSet, "M830.837T11.111")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M830.837T11.111","NA","NA", 4, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M883.492T15.092")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M883.492T15.092","NA","NA", 5, "png", 72)
mSet<-UpdateLoadingCmpd(mSet, "M367.151T397.982")
mSet<-SetCmpdSummaryType(mSet, "boxplot")
mSet<-PlotCmpdSummary(mSet, "M367.151T397.982","NA","NA", 6, "png", 72)
mSet<-PCA.Anal(mSet)
mSet<-PlotPCAPairSummary(mSet, "pca_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPCAScree(mSet, "pca_scree_0_", "png", 72, width=NA, 5)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPCALoading(mSet, "pca_loading_0_", "png", 72, width=NA, 1,2);
mSet<-PlotPCABiplot(mSet, "pca_biplot_0_", "png", 72, width=NA, 1,2)
mSet<-PlotPCA3DLoading(mSet, "pca_loading3d_0_", "json", 1,2,3)
mSet<-PlotPCA2DScore(mSet, "pca_score2d_1_", "png", 72, width=NA, 1,2,0.95,1,0, "na")
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotHCTree(mSet, "tree_1_", "png", 72, width=NA, "pearson", "ward.D")
mSet<-PlotHCTree(mSet, "tree_2_", "png", 72, width=NA, "spearman", "ward.D")
mSet<-PlotHCTree(mSet, "tree_3_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, T, T, NULL, T, F, T, T,  T,T)
mSet<-SaveTransformedData(mSet)
