# PID of current job: 3797942
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 10, "iqr", 0, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-Calculate.ANOVA.posthoc(mSet, "fisher", 0.05)
mSet<-ANOVA.Anal(mSet, F, 1.0, FALSE)
mSet<-PlotANOVA(mSet, "aov_1_", "png", 72, width=NA)
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 25, "none", -1, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, FALSE)
mSet<-PlotANOVA(mSet, "aov_1_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 1.0, FALSE)
mSet<-PlotANOVA(mSet, "aov_2_", "png", 72, width=NA)
mSet<-Calculate.ANOVA.posthoc(mSet, "fisher", 0.05)
mSet<-ANOVA.Anal(mSet, F, 0.43232, FALSE)
mSet<-PlotANOVA(mSet, "aov_3_", "png", 72, width=NA)
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, T, T, NULL, T, F, T, T,  T,T)
mSet<-PlotHeatMap(mSet, "heatmap_2_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, F, T, NULL, T, F, T, T,  T,T)
mSet<-PlotSubHeatMap(mSet, "heatmap_3_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 8,8, 10.0,0.02,10, 10, "tanova", 125, T, T, T, F, T, T, T,T,"overview")
mSet<-SaveTransformedData(mSet)
