# PID of current job: 4164476
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-SanityCheckData(mSet)
mSet<-FilterVariable(mSet, "F", 25, "iqr", 0, "mean", 0)
mSet<-PreparePrenormData(mSet)
mSet<-GetGroupNames(mSet, "")
feature.nm.vec <- c("")
smpl.nm.vec <- c("C12.1","F12.3")
grp.nm.vec <- c("Control","Fusarium")
mSet<-UpdateData(mSet, T)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "CompNorm", "LogNorm", "ParetoNorm", "sodium_formate", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-FC.Anal(mSet, 2.0, 0, FALSE)
mSet<-PlotFC(mSet, "fc_0_", "png", 72, width=NA)
mSet<-FC.Anal(mSet, 2.0, 1, FALSE)
mSet<-PlotFC(mSet, "fc_1_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, TRUE, "fdr", FALSE)
mSet<-PlotTT(mSet, "tt_0_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, T, 0.05, FALSE, FALSE, "raw", FALSE)
mSet<-PlotTT(mSet, "tt_1_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, FALSE, "raw", FALSE)
mSet<-PlotTT(mSet, "tt_2_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, FALSE, "raw", FALSE)
mSet<-PlotTT(mSet, "tt_3_", "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, F, 0.1, TRUE, "raw")
mSet<-PlotVolcano(mSet, "volcano_0_",1, 0, "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 1, F, 0.1, FALSE, "raw")
mSet<-PlotVolcano(mSet, "volcano_1_",1, 0, "png", 72, width=NA)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 4)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0, "na")
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PlotHCTree(mSet, "tree_0_", "png", 72, width=NA, "euclidean", "ward.D")
mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 15, T, T, NULL, T, F, T, T,  T,T)
mSet<-PlotSubHeatMap(mSet, "heatmap_2_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 15, "tanova", 63, T, T, T, F, T, T, T,T,"overview")
mSet<-PlotHeatMap(mSet, "heatmap_3_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 5, T, T, NULL, T, F, T, T,  T,T)
mSet<-PlotHeatMap(mSet, "heatmap_4_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 5, T, T, NULL, T, F, T, T,  T,F)
mSet<-PlotHeatMap(mSet, "heatmap_5_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 10, T, T, NULL, T, F, T, T,  T,F)
mSet<-PlotSubHeatMap(mSet, "heatmap_6_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 5, "tanova", 63, T, T, T, F, T, T, T,T,"overview")
mSet<-PlotSubHeatMap(mSet, "heatmap_7_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", 12,8, 10.0,0.02,20, 6, "tanova", 63, T, T, T, F, T, T, T,T,"overview")
mSet<-SaveTransformedData(mSet)
